#!/usr/bin/env python

import sys
import wx
import traceback
import os

import plover.gui.main
import plover.oslayer.processlock

def show_error(title, message):
    app = wx.PySimpleApp()
    print message
    alert_dialog = wx.MessageDialog(None,
                                    message,
                                    title,
                                    wx.OK | wx.ICON_INFORMATION)
    alert_dialog.ShowModal()
    alert_dialog.Destroy()

try:
    # Ensure only one instance of Plover is running at a time.
    with plover.oslayer.processlock.PloverLock():
        gui = plover.gui.main.PloverGUI()
        gui.MainLoop()
except plover.oslayer.processlock.LockNotAcquiredException:
    show_error('Error', 'Another instance of Plover is already running.')
except:
    show_error('Unexpected error', traceback.format_exc())
    os._exit(1)